-- Optional employee identity, personal, employment, bank, and document fields.
-- Run this after 001_split_app_users_into_role_tables.sql for an existing database.

ALTER TABLE IF EXISTS super_admins ALTER COLUMN last_name DROP NOT NULL;
ALTER TABLE IF EXISTS admins ALTER COLUMN last_name DROP NOT NULL;
ALTER TABLE IF EXISTS managers ALTER COLUMN last_name DROP NOT NULL;
ALTER TABLE IF EXISTS trainers ALTER COLUMN last_name DROP NOT NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN last_name DROP NOT NULL;

ALTER TABLE IF EXISTS admins
    ADD COLUMN IF NOT EXISTS date_of_birth DATE,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(30),
    ADD COLUMN IF NOT EXISTS blood_group VARCHAR(5),
    ADD COLUMN IF NOT EXISTS personal_email VARCHAR(100),
    ADD COLUMN IF NOT EXISTS alternate_phone VARCHAR(20),
    ADD COLUMN IF NOT EXISTS emergency_contact VARCHAR(100),
    ADD COLUMN IF NOT EXISTS emergency_phone VARCHAR(20),
    ADD COLUMN IF NOT EXISTS current_address VARCHAR(300),
    ADD COLUMN IF NOT EXISTS permanent_address VARCHAR(300),
    ADD COLUMN IF NOT EXISTS city VARCHAR(80),
    ADD COLUMN IF NOT EXISTS state VARCHAR(80),
    ADD COLUMN IF NOT EXISTS pincode VARCHAR(20),
    ADD COLUMN IF NOT EXISTS employment_type VARCHAR(50),
    ADD COLUMN IF NOT EXISTS work_location VARCHAR(100),
    ADD COLUMN IF NOT EXISTS reporting_manager_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS probation_end_date DATE,
    ADD COLUMN IF NOT EXISTS pan_number VARCHAR(20),
    ADD COLUMN IF NOT EXISTS aadhar_number VARCHAR(20),
    ADD COLUMN IF NOT EXISTS bank_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS bank_account_number VARCHAR(40),
    ADD COLUMN IF NOT EXISTS bank_ifsc_code VARCHAR(20),
    ADD COLUMN IF NOT EXISTS bank_account_type VARCHAR(30),
    ADD COLUMN IF NOT EXISTS qualification_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS certification_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS id_proof_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS address_proof_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS resume_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS offer_letter_document_url VARCHAR(500);

ALTER TABLE IF EXISTS managers
    ADD COLUMN IF NOT EXISTS date_of_birth DATE,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(30),
    ADD COLUMN IF NOT EXISTS blood_group VARCHAR(5),
    ADD COLUMN IF NOT EXISTS personal_email VARCHAR(100),
    ADD COLUMN IF NOT EXISTS alternate_phone VARCHAR(20),
    ADD COLUMN IF NOT EXISTS emergency_contact VARCHAR(100),
    ADD COLUMN IF NOT EXISTS emergency_phone VARCHAR(20),
    ADD COLUMN IF NOT EXISTS current_address VARCHAR(300),
    ADD COLUMN IF NOT EXISTS permanent_address VARCHAR(300),
    ADD COLUMN IF NOT EXISTS city VARCHAR(80),
    ADD COLUMN IF NOT EXISTS state VARCHAR(80),
    ADD COLUMN IF NOT EXISTS pincode VARCHAR(20),
    ADD COLUMN IF NOT EXISTS employment_type VARCHAR(50),
    ADD COLUMN IF NOT EXISTS work_location VARCHAR(100),
    ADD COLUMN IF NOT EXISTS reporting_manager_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS probation_end_date DATE,
    ADD COLUMN IF NOT EXISTS pan_number VARCHAR(20),
    ADD COLUMN IF NOT EXISTS aadhar_number VARCHAR(20),
    ADD COLUMN IF NOT EXISTS bank_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS bank_account_number VARCHAR(40),
    ADD COLUMN IF NOT EXISTS bank_ifsc_code VARCHAR(20),
    ADD COLUMN IF NOT EXISTS bank_account_type VARCHAR(30),
    ADD COLUMN IF NOT EXISTS qualification_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS certification_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS id_proof_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS address_proof_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS resume_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS offer_letter_document_url VARCHAR(500);

ALTER TABLE IF EXISTS trainers
    ADD COLUMN IF NOT EXISTS date_of_birth DATE,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(30),
    ADD COLUMN IF NOT EXISTS blood_group VARCHAR(5),
    ADD COLUMN IF NOT EXISTS personal_email VARCHAR(100),
    ADD COLUMN IF NOT EXISTS alternate_phone VARCHAR(20),
    ADD COLUMN IF NOT EXISTS emergency_contact VARCHAR(100),
    ADD COLUMN IF NOT EXISTS emergency_phone VARCHAR(20),
    ADD COLUMN IF NOT EXISTS current_address VARCHAR(300),
    ADD COLUMN IF NOT EXISTS permanent_address VARCHAR(300),
    ADD COLUMN IF NOT EXISTS city VARCHAR(80),
    ADD COLUMN IF NOT EXISTS state VARCHAR(80),
    ADD COLUMN IF NOT EXISTS pincode VARCHAR(20),
    ADD COLUMN IF NOT EXISTS employment_type VARCHAR(50),
    ADD COLUMN IF NOT EXISTS work_location VARCHAR(100),
    ADD COLUMN IF NOT EXISTS reporting_manager_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS probation_end_date DATE,
    ADD COLUMN IF NOT EXISTS pan_number VARCHAR(20),
    ADD COLUMN IF NOT EXISTS aadhar_number VARCHAR(20),
    ADD COLUMN IF NOT EXISTS bank_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS bank_account_number VARCHAR(40),
    ADD COLUMN IF NOT EXISTS bank_ifsc_code VARCHAR(20),
    ADD COLUMN IF NOT EXISTS bank_account_type VARCHAR(30),
    ADD COLUMN IF NOT EXISTS qualification_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS certification_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS id_proof_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS address_proof_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS resume_document_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS offer_letter_document_url VARCHAR(500);
